// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PaymentattemptColumns holds the columns for the "paymentattempt" table.
	PaymentattemptColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "payment_method", Type: field.TypeString},
		{Name: "processor", Type: field.TypeString, Nullable: true},
		{Name: "processor_ref", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "payment_hash", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString},
		{Name: "added_on", Type: field.TypeTime, Nullable: true},
		{Name: "updated_on", Type: field.TypeTime, Nullable: true},
		{Name: "payment_intent_id", Type: field.TypeInt},
	}
	// PaymentattemptTable holds the schema information for the "paymentattempt" table.
	PaymentattemptTable = &schema.Table{
		Name:       "paymentattempt",
		Columns:    PaymentattemptColumns,
		PrimaryKey: []*schema.Column{PaymentattemptColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paymentattempt_paymentintent_payment_attempts",
				Columns:    []*schema.Column{PaymentattemptColumns[11]},
				RefColumns: []*schema.Column{PaymentintentColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PaymentintentColumns holds the columns for the "paymentintent" table.
	PaymentintentColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "customer_email", Type: field.TypeString},
		{Name: "customer_phone", Type: field.TypeString},
		{Name: "customer_address", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString},
		{Name: "added_on", Type: field.TypeTime, Nullable: true},
		{Name: "updated_on", Type: field.TypeTime, Nullable: true},
	}
	// PaymentintentTable holds the schema information for the "paymentintent" table.
	PaymentintentTable = &schema.Table{
		Name:       "paymentintent",
		Columns:    PaymentintentColumns,
		PrimaryKey: []*schema.Column{PaymentintentColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PaymentattemptTable,
		PaymentintentTable,
	}
)

func init() {
	PaymentattemptTable.ForeignKeys[0].RefTable = PaymentintentTable
	PaymentattemptTable.Annotation = &entsql.Annotation{
		Table: "paymentattempt",
	}
	PaymentintentTable.Annotation = &entsql.Annotation{
		Table: "paymentintent",
	}
}
