// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PaymentAttempt is the predicate function for paymentattempt builders.
type PaymentAttempt func(*sql.Selector)

// PaymentIntent is the predicate function for paymentintent builders.
type PaymentIntent func(*sql.Selector)
