apiVersion: v1
kind: Pod
metadata:
  name: atlas
spec:
  containers:
  - name: atlas
    image: atlas:latest
    imagePullPolicy: IfNotPresent  # or IfNotPresent
    env:
      - name: MYSQL_DSN 
        value: "root:{password}@tcp(host.docker.internal:3306)/test?parseTime=true"
      - name: cashfree.appId
        value: "1848d0ce8441fb8ffa258bc98481"
      - name: cashfree.secret
        value: ""
