apiVersion: v1
kind: Pod
metadata:
  name: atlas-admin-ui
spec:
  containers:
  - name: atlas-admin-ui
    image: atlas-admin-ui:latest
    imagePullPolicy: IfNotPresent  # or IfNotPresent
    env:
      - name: MYSQL_DSN 
        value: "root:{password}@tcp(host.docker.internal:3306)/test?parseTime=true"
